### ISSUE TITLE
ProjectURL shouldn't be hardcoded

### ISSUE THREAD

**Issue by elharony** [mohamednajiub/wordpress-gulp-workflow#7]
I liked your package, great work so far, @mohamednajiub !

But I noticed that you're assuming that my Wordpress project has to be directly first-level inside `htdocs/`, otherwise BrowserSync won't reload my project, in [`gulpfile.babel.js`](https://github.com/mohamednajiub/wp-workflow/blob/master/gulpfile.babel.js#L58):
```js
/********** Theme initialization **********/
let project_name = config.project_name;
```

 Let's say `my-awesome-project` is localted at `htdocs/projects/my-awesome-project/`, it won't work with your package.

I hope you fix it and keep maintaining this package. Great work!!!! 👏

**Comment by mohamednajiub** [comment]
Hey, Yahya 👋👋
thanks for using wp-workflow 
I changed it in  #8 that now you can add project path instead of project name to take control of your project path.
